# retirado de um projeto ruby apenas para vizualizacao
# version: 2
# updates:
# - package-ecosystem: npm
#   directory: "/"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
# - package-ecosystem: github-actions
#   directory: "/"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
